### ISSUE TITLE
Tell everyone about metalsmith-prism in the metalsmith.io site

### ISSUE THREAD

**Issue by eliotsykes** [Availity/metalsmith-prism#1]

**Comment by robmcguinness** [comment]
Waiting on pull request https://github.com/segmentio/metalsmith.io/pull/95

**Comment by eliotsykes** [comment]
@robmcguinness thanks for writing metalsmith-prism btw :+1:

**Comment by robmcguinness** [comment]
done! thanks!

![image](https://cloud.githubusercontent.com/assets/281070/8637635/579c0fac-2869-11e5-9f2d-b5cb1627e2fd.png)
