### ISSUE TITLE
Having trouble getting to work with Markdown code

### ISSUE THREAD

**Issue by jamiewilson** [Availity/metalsmith-prism#13]
Hey, so I've got `metalsmith-prism` installed and I'm calling like so:

```javascript
var metalsmith  = require('metalsmith');
var markdown  = require('metalsmith-markdown');
var prism  = require('metalsmith-prism');

metalsmith(__dirname)
  .use(markdown({
    gfm: true,
    tables: true,
    smartypants: true,
    smartLists: true,
    sanitize: false,
    langPrefix: 'language-'
  })
  .use(prism)
  .build()
```
But as you can see…
![screen shot 2015-11-13 at 10 43 07 am](https://cloud.githubusercontent.com/assets/3308673/11151560/7333d9ca-89f3-11e5-9412-ee30d534e18f.png)
the code isn't getting parsed. 

Any ideas? Is this a metalsmith-markdown issue?

**Comment by jamiewilson** [comment]
Oops. pesky parenthesis! corrected to `.use(prism())` :facepalm:

**Comment by robmcguinness** [comment]
:grinning:
