### ISSUE TITLE
Add support for specifying tag name

### ISSUE THREAD

**Issue by taylorzane** [Availity/metalsmith-prism#14]
Howdy,

I've been using your metalsmith plugin, and I recently transitioned from using Markdown to using Jade for  my blog post templating engine. I noticed that using the `code(class='language-haskell')` syntax doesn't format the code contents correctly. (It has gaps between lines). But when I use the `pre(class='language-haskell')` syntax, everything comes out fine. I'm not sure where this bug is happening. It looks odd in all browsers.

If there was a plugin option, say `tagName` that would allow one to specify the tag that they want prism to highlight, that would be great. Then you could even do something like... ```h1(class="language-haskell") foo bar = bar + (3 `div` bar)``` if you really wanted to.

Here's a screenshot of the odd behavior.

Using `code`:
![image](https://cloud.githubusercontent.com/assets/5092987/12800038/06e9e0e4-ca98-11e5-96da-a14b2fb95c4a.png)

Using `pre`:
![image](https://cloud.githubusercontent.com/assets/5092987/12800056/20a2adcc-ca98-11e5-8742-98f0b45e34d0.png)

— Taylor Zane Glaeser

**Comment by taylorzane** [comment]
P.S. Currently I'm getting around this using the syntax:

```jade
pre(class='language-coffeescript')
  code(class='language-coffeescript').
    foo = (bar) ->
      # etc...
```

**Comment by robmcguinness** [comment]
**metalsmith-prism** is just a wrapper around Prism.js I believe it only works with the `<code>` tag. 

* https://github.com/PrismJS/prism/issues/867
* https://github.com/PrismJS/prism/pull/869

I'm not sure why the highlighting isn't properly formatted without `<pre>` tag but when I have a minute I'll take a peek.

**Comment by taylorzane** [comment]
Well I did a quick hack to [lib/index.js](https://github.com/Availity/metalsmith-prism/blob/master/lib/index.js#L51) and changed it to `$(options.tagName || 'code')` and I'm able to highlight anything.

I can submit a PR, I just didn't know if the maintainer had a preferred way to do this. I figured I'd open a discussion about it prior to making any modifications.

Example:
![image](https://cloud.githubusercontent.com/assets/5092987/12817298/fc5ba5ca-cb16-11e5-9021-c9f700d0521e.png)

**Comment by robmcguinness** [comment]
Seems simple enough.  In the PR:

- include unit test
- update the README options section

**Comment by robmcguinness** [comment]
It looks like Prism automatically adds the appropriate language class [prism.js#L731](https://github.com/PrismJS/prism/blob/bd479f1d5ff0855b4c50168c1a82c91b2db191f2/prism.js#L731) to the `<pre>` parent but only when the function [fileHighlight()](https://github.com/PrismJS/prism/blob/bd479f1d5ff0855b4c50168c1a82c91b2db191f2/prism.js#L731) is run on [DOMContentLoaded](https://github.com/PrismJS/prism/blob/bd479f1d5ff0855b4c50168c1a82c91b2db191f2/prism.js#L772)...which is never trigged with this plugin.

Would adding that same behavior into this plugin satisfy your request?  I'm trying to stay as close to the Prism.js concepts as much as possible.

[Under Basic Usage](http://prismjs.com/#basic-usage)
> Prism does its best to encourage good authoring practices. Therefore, it only works with `<code>` elements, since marking up code without a `<code>` element is semantically invalid.
