### ISSUE TITLE
No styles applied

### ISSUE THREAD

**Issue by frederikprijck** [Availity/metalsmith-prism#22]
Hi,

I'm sorry, I know generally github issues are not supposed to be for getting help. But I'm abit stuck here and afaik I did follow the readme steps.

I've never used prismjs, so I'm unsure this is related to `metalsmith-prism` at all.

- Ive installed metalsmith-prism: https://github.com/frederikprijck/blog/blob/master/package.json#L23
- added metalsmith-prism to my metalsmith build: https://github.com/frederikprijck/blog/blob/master/metalsmith.common.js#L40
- added a code block in my blog post: https://github.com/frederikprijck/blog/blob/master/src/articles/test.md

When running metalsmith, prism kicks as expected: 

```
<code class="language-css">
  <span class="token selector">p</span> 
  <span class="token punctuation">{</span> 
  <span class="token property">color</span>
  <span class="token punctuation">:</span> red <span class="token punctuation">}</span>
</code>
```
and
```
<pre class="language-javascript line-numbers">  <code class="language-javascript">
  <span class="token keyword">const</span> someFunction <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span><span class="token operator">&gt;</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'ok'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
  </code>
</pre>
```
However, no styling is applied. I'm guessing I need to include themes, but as the readme doesn't mention anything I'm not sure if I need to or whether or not something is wrong in my setup.

Note: lineNumbers is set to `true`, but no (unstyled) line numbers are being applied neither.

----
The readme mentions:
> To use with Markdown code blocks rendered by metalsmith-markdown

But it looks like doing so, doesn't change anything. So I'm not sure if this is still required when using markdown?

**Comment by frederikprijck** [comment]
Adding CDN links did the trick, which makes sense.

**Comment by robmcguinness** [comment]
@frederikprijck you are correct that styles are not applied automatically and must be included by some other means using metalsmith (I use webpack to include styles for code blocks).  You can find a discussion about line-number here https://github.com/Availity/metalsmith-prism/pull/15 and see if any of those solutions works for you.  Line number support is on my todo but I haven't had the time to investigate a solution.

**Comment by frederikprijck** [comment]
@robmcguinness Alright, thanks!

Unrelated: Any good example on integrating webpack with metalsmith? I'm familiar with webpack, just pretty new to metalsmith 🙈

**Comment by robmcguinness** [comment]
Here is how I built it (so many ways to achieve same goal):

- metalsmith programatic configuration https://github.com/Availity/availity-angular/blob/master/dev/metalsmith.js
- webpack entry file for docs https://github.com/Availity/availity-angular/blob/master/docs/js/index.js
- webpack configuration for docs https://github.com/Availity/availity-angular/blob/master/webpack.config.docs.js
- template partial used by Metalsmith which includes the assets from the Webpack output folder https://github.com/Availity/availity-angular/blob/master/docs/layouts/partials/header.html

There is a metalsmith plugin for webpack but I have never used it.

**Comment by dylanspurgin** [comment]
Thanks for the nice plugin. I had to figure this out by searching through closed issues. It seems like a good idea to add this information to the quickstart section of the README.

**Comment by robmcguinness** [comment]
@dylanspurgin added! 👍
