### ISSUE TITLE
Make HTML decode configurable

### ISSUE THREAD

**Issue by misterdai** [Availity/metalsmith-prism#9]
I've run into an issue where the module "metalsmith-markdown" will escape the HTML characters within my code samples for me, turning `<` into `&lt;`.  However, when "metalsmith-prism" comes along and processes the same code sample, it doesn't decode the HTML entities for prism.  The end result is that `&lt;` turning into `&amp;lt;`, which messes up the original code sample.

I'm sure this was probably written this way for a good reason, so that's why I'm suggesting that making it configurable would at least provide a workaround to [others working this way](https://github.com/nodejs/new.nodejs.org/blob/master/build.js).

---

Example:

    Here is some code

    ```markup
    <html>
    ```

Becomes (after metalsmith-markdown)

    <p>Here is some code</p>
    
    <pre><code class="language-markup">
    &lt;html&gt;
    </code></pre>

Then (after metalsmith-prism)

    <p>Here is some code</p>
    
    <pre><code class="language-markup">
    <span class="token entity" title="&lt;">&amp;lt;</span>html<span class="token entity" title="&gt;">&amp;gt;</span>
    </code></pre>

If I remove the check for `language === 'markup'` check that decides on decoding, it comes out the other end correctly.

**Comment by robmcguinness** [comment]
i'll take a look by end of week.

**Comment by misterdai** [comment]
:+1: cheers, I've worked around it locally for now, so no rush.

**Comment by robmcguinness** [comment]
@misterdai was this the workaround?

```javascript

const markdown = require('metalsmith-markdown')
const renderer = new marked.Renderer()

.use(markdown({
  langPrefix: 'language-',
  renderer: renderer
}))
```

**Comment by misterdai** [comment]
My workaround was to just remove the ternary check for a language of `markup` from this line: https://github.com/Availity/metalsmith-prism/blob/b79a4e976ab11c1ee08a2e10f78b011dd6e48cd8/lib/index.js#L64

So it'd read `var html = he.decode($this.html());` instead.  As I said, wasn't sure why you put that check in there, guessing you might not have had the source encoded in your usage.  Which is why I'm thinking that if it's configurable, it'll work for everyone ;)

**Comment by robmcguinness** [comment]
yes you are correct! :smirk: I'll make the necessary adjustments.

**Comment by robmcguinness** [comment]
@misterdai does #11 look reasonable?
